---
# install mysql, create a new user & db

- name: Install mysql
  apt: name={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
   - mysql-server-5.6
   - python-mysqldb

# probably not needed
- name: start mysql
  service: name=mysql state=started enabled=yes

- name: Copy database to remote host
  copy: src={{ dbdump }} dest=/tmp/dbdump.sql mode=400

- name: create db root user
  mysql_user: 
    name: root
    host: "{{ item }}"
    password: "{{ rootdbpassword }}"
    login_user: root
    login_password: "{{ rootdbpassword }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy MySQL options file
  template: src=.my.cnf.j2 dest=~/.my.cnf mode=400

- name: Create db
  mysql_db: name={{ dbname }} state=present

- name: populate db
  mysql_db: name={{ dbname }} state=import target=/tmp/dbdump.sql

- name: delete the .sql on the remote host
  file: path=/tmp/dbdump.sql state=absent

- name: create db user
  mysql_user: name={{ dbuser }}  password={{ dbpassword }} priv={{ dbname }}.*:ALL state=present

- name: copy the sql update script
  template: src=update_url.sql.j2 dest=/tmp/update_url.sql

- name: update any old urls in db
  shell: mysql {{ dbname }} < /tmp/update_url.sql
